# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(536, 552)
        Main.setStyleSheet("background-color:rgb(100, 167, 58)")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 521, 511))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_area_edit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.text_area_edit.setStyleSheet("background-color:rgb(232, 232, 232); border: 3px solid black;border-radius:5px")
        self.text_area_edit.setObjectName("text_area_edit")
        self.horizontalLayout_4.addWidget(self.text_area_edit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_zametki = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_zametki.setStyleSheet(" border: 3px solid black;border-radius:5px;background-color:rgb(232, 232, 232)")
        self.label_zametki.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zametki.setObjectName("label_zametki")
        self.verticalLayout.addWidget(self.label_zametki)
        self.list_zamitok = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.list_zamitok.setStyleSheet("background-color:rgb(232, 232, 232); border: 3px solid black;border-radius:5px")
        self.list_zamitok.setObjectName("list_zamitok")
        self.verticalLayout.addWidget(self.list_zamitok)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_create_zam = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_create_zam.setStyleSheet("border: 3px solid black;border-radius:5px;background-color:rgb(72, 189, 0);")
        self.btn_create_zam.setObjectName("btn_create_zam")
        self.horizontalLayout.addWidget(self.btn_create_zam)
        self.btn_delete_zam = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_delete_zam.setStyleSheet(" border: 3px solid black;border-radius:5px;background-color:rgb(255, 0, 4); ")
        self.btn_delete_zam.setObjectName("btn_delete_zam")
        self.horizontalLayout.addWidget(self.btn_delete_zam)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_save_zam = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_save_zam.setStyleSheet("background-color:rgb(72, 189, 0); border: 3px solid black;border-radius:5px;")
        self.btn_save_zam.setObjectName("btn_save_zam")
        self.verticalLayout.addWidget(self.btn_save_zam)
        self.label_tegs = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_tegs.setStyleSheet(" border: 3px solid black;border-radius:5px;background-color:rgb(232, 232, 232)")
        self.label_tegs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tegs.setObjectName("label_tegs")
        self.verticalLayout.addWidget(self.label_tegs)
        self.list_tegs = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.list_tegs.setStyleSheet("background-color:rgb(232, 232, 232); border: 3px solid black;border-radius:5px")
        self.list_tegs.setObjectName("list_tegs")
        self.verticalLayout.addWidget(self.list_tegs)
        self.search_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.search_line.setStyleSheet(" border: 3px solid black;border-radius:5px;\n"
"background-color:rgb(232, 232, 232)")
        self.search_line.setInputMask("")
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.verticalLayout.addWidget(self.search_line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_add.setStyleSheet("background-color:rgb(72, 189, 0); border: 3px solid black;border-radius:5px;")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_3.addWidget(self.btn_add)
        self.btn_dontadd = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_dontadd.setStyleSheet("background-color:rgb(255, 0, 4); border: 3px solid black;border-radius:5px;")
        self.btn_dontadd.setObjectName("btn_dontadd")
        self.horizontalLayout_3.addWidget(self.btn_dontadd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.search_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.search_btn.setStyleSheet("background-color:rgb(72, 189, 0); border: 3px solid black;border-radius:5px;")
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Розумні замітки"))
        self.label_zametki.setText(_translate("Main", "Список заміток"))
        self.btn_create_zam.setText(_translate("Main", "Створити замітку"))
        self.btn_delete_zam.setText(_translate("Main", "Видалити замітку"))
        self.btn_save_zam.setText(_translate("Main", "Зберегти замітку"))
        self.label_tegs.setText(_translate("Main", "Список тегів"))
        self.search_line.setPlaceholderText(_translate("Main", "Введіть тег"))
        self.btn_add.setText(_translate("Main", "Додати до замтіки"))
        self.btn_dontadd.setText(_translate("Main", "Відкрипити від замітки"))
        self.search_btn.setText(_translate("Main", "Шукати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
